name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # REQUIRED for OIDC
  contents: read

jobs:
  deploy-iac:
    runs-on: terraform-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------- AUTHENTICATE WITH AWS USING OIDC ----------
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::780139020397:role/GithubActionsTerraformRole
          role-session-name: terraform-session
          aws-region: us-east-1

      # ---------- TERRAFORM ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install tfsec for security scanning
        run: |
          curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.11/tfsec-linux-amd64
          chmod +x tfsec
          ./tfsec --version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec Security Scan
        run: ./tfsec . || true

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # ---------- KUBERNETES DEPLOYMENTS ----------
      # - name: Install kubectl
      #   run: |
      #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      #     chmod +x ./kubectl
      #     sudo mv ./kubectl /usr/local/bin/kubectl

      # - name: Authenticate to EKS Cluster
      #   run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region us-east-1

      # - name: Deploy ClusterIssuer
      #   run: kubectl apply -f ClusterIssuer.yaml

      # - name: Deploy ArgoCD ingress
      #   run: kubectl apply -f ingress-argocd.yaml -n argocd
